### ISSUE TITLE
两个疑问

### ISSUE THREAD

**Issue by BrianGong** [ilovin/lstm_ctc_ocr#14]
作者你好，我有两个疑问：
1. 我看了网络的代码在LSTM部分首先是一个双向的LSTM ，然后将输出再作为一个双层单向的LSTM，之后的输出再做一个映射（tf.matmul(lstm_out,W)+b）。这么设计的想法是什么？
2.这个网络的泛化能力怎么样？ 
    我用随机生产的验证码训练网络， 准确率达到97%，但是换做个测试数据集，比如在word打一串数字然后截屏，这样的识别结果准确率为0，您觉得问题出在哪？

**Comment by bidai541** [comment]
遇到了相同的问题，@ilovin 试着其他字体，像身份证号，基本识别不出来呢

**Comment by ilovin** [comment]
- encoder-decoder
- 验证码和身份证号相差甚远，训练数据决定了最终的结果，在一个issue中我放了一个身份证号训练好的model
