### ISSUE TITLE
i have run the code，the rusult acc is 86%，my goal is 90%+ ,how  to impove this?

### ISSUE THREAD

**Issue by dotsonliu** [ilovin/lstm_ctc_ocr#22]
7/7 8:41:54 Epoch 89/10000, accuracy = 0.864,avg_train_cost = 0.354, lastbatch_err = 0.034, time = 144.714,lr=0.00000000

**Comment by ilovin** [comment]
use the beta version, which has highest acc.
the master version 96% is on training dataset, 
however the beta and dev version, the acc is on validation dataset
