### ISSUE TITLE
i used chinese to run the code,but there has something wrong?  acc is o,avg_train_cost <0? 

### ISSUE THREAD

**Issue by dotsonliu** [ilovin/lstm_ctc_ocr#24]
![image](https://user-images.githubusercontent.com/28289146/30841340-8308b534-a2ae-11e7-8349-63eb68c7934d.png)

![image](https://user-images.githubusercontent.com/28289146/30841327-7717cab2-a2ae-11e7-9dbb-8143400b0e37.png)

**Comment by dotsonliu** [comment]
@ilovin ,i dont know whats wrong. why is this? i also use chinese index which coverd all chinese char. the dataset has 50w images. i donot know whats wrong? 
![image](https://user-images.githubusercontent.com/28289146/30841433-fc46170c-a2ae-11e7-9270-74e6191122ea.png)

**Comment by ilovin** [comment]
assume you are using the beta version.
the name of your image cannot match the `regex expression`(read the README)
or you can modify the code in 
https://github.com/ilovin/lstm_ctc_ocr/blob/dev/lib/lstm/utils/tf_records.py#L54
if you are using the master version, you may also modify the related code.
make a comment if it works.

**Comment by dotsonliu** [comment]
@ilovin i use chinese charset，how many images you advise？ i used 1000w imags to train the model（master version），its too slower，is beta better?

**Comment by ilovin** [comment]
it is much better, however you need to modify the code from generating image to reading image

**Comment by dotsonliu** [comment]
@ilovin I has modify the code,when i train the crnn(master),i use 300w+ chinese images, but when epoch is 2,lr is too small,near zero,  and acc is 57%,not go better,how can i resolve the problem?
![Uploading image.png…]()

**Comment by dotsonliu** [comment]
![image](https://user-images.githubusercontent.com/28289146/30998085-bd4c2f8a-a4fe-11e7-938e-daf8c9c2e5be.png)

**Comment by ilovin** [comment]
read the readme, change the super parameter
https://github.com/ilovin/lstm_ctc_ocr#some-details
