### ISSUE TITLE
Master branch cannot converge

### ISSUE THREAD

**Issue by GabrielLin** [ilovin/lstm_ctc_ocr#25]
The latest master branch cannot converge.  I have read all other relative issues and changed decay_steps to 100000. It cannot helps. Could you give me some suggestions. I do not want to use warpCTC. Thanks.

**Comment by ilovin** [comment]
for the master branch, it takes 20000 steps to begin converge.
for the beta branch, it takes 20000 steps to get acc for about 96%.

**Comment by ilovin** [comment]
welcome to re=open, if you have further question
