### ISSUE TITLE
warp-ctc不能绑定到TensorFlow1.1

### ISSUE THREAD

**Issue by junedgar** [ilovin/lstm_ctc_ocr#3]
warp-ctc 编译以及setup都没有错误，在import  warpctc_tensorflow的时候出现错误：
``File "<stdin>", line 1, in <module>
File "/Users/edgar/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/warpctc_tensorflow-0.1-py2.7-macosx-10.7-x86_64.egg/warpctc_tensorflow/__init__.py", line 7, in <module>
  _warpctc = tf.load_op_library(lib_file)
File "/Users/edgar/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
  None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/edgar/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/warpctc_tensorflow-0.1-py2.7-macosx-10.7-x86_64.egg/warpctc_tensorflow/kernels.so, 6): Library not loaded: @rpath/libwarpctc.dylib
Referenced from: /Users/edgar/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/warpctc_tensorflow-0.1-py2.7-macosx-10.7-x86_64.egg/warpctc_tensorflow/kernels.so
Reason: image not found``
有没有人遇到相同问题的呢

**Comment by hanghang2333** [comment]
我也有同样的问题,不知道如何做啊.我目前是已经pip安装的tensorflow1.1.0.如何才能使用wrapctc呢.看https://github.com/baidu-research/warp-ctc/tree/master/tensorflow_binding这里说的还要下载源码,那么是要重新从源码编译安装嘛,那么又如何下载到1.1的源码啊....问题比较多,谢谢解答啦

**Comment by ilovin** [comment]
warpCTC里的issue https://github.com/baidu-research/warp-ctc/issues/80 有人提到过这个问题，1.1.0 跑官方的测试代码会出问题，但是可能还是能用的，没具体测试过，可以尝试使用`virtualenv` 便于折腾
warpCTC的安装方法，那个页面里的README已经说的挺详细的，耐心一些照做就好
