### ISSUE TITLE
Using Tensorflow CTC on Dev and Beta instead of Warp CTC

### ISSUE THREAD

**Issue by jvgonzalvo** [ilovin/lstm_ctc_ocr#36]
Is it possible to replace Warp CTC withTensorflow CTC for the dev and beta branches of this repository? I plan on using this for mobile and unfortunately, tensorflow android doesn't support warp ctc.

**Comment by ilovin** [comment]
of course, yes. Actually, someone has already done it.
https://github.com/ilovin/lstm_ctc_ocr/issues/34

**Comment by jvgonzalvo** [comment]
Alright, I'll try it out for myself. Thank you 👍
