### ISSUE TITLE
字符的长度应该是63个吧

### ISSUE THREAD

**Issue by fancyerii** [ilovin/lstm_ctc_ocr#51]
有效的字符是a-zA-Z0-9 62个，然后加上一个空(epsilon)，共63个。我测试了一下把它改成63，效果没有任何变化。

$ git diff
diff --git a/lib/lstm/config.py b/lib/lstm/config.py
index 3b1a322..e61cc3b 100644
--- a/lib/lstm/config.py
+++ b/lib/lstm/config.py
@@ -20,7 +20,7 @@ __C.IMG_HEIGHT = 32
 __C.MAX_CHAR_LEN = 6
 __C.BLANK_TOKEN=0
 __C.CHARSET = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
-__C.NCLASSES = len(__C.CHARSET)+2
+__C.NCLASSES = len(__C.CHARSET)+1

**Comment by ilovin** [comment]
https://github.com/ilovin/lstm_ctc_ocr/issues/35
https://github.com/ilovin/lstm_ctc_ocr/issues/49
it's only a trick

**Comment by fancyerii** [comment]
哦，是为了兼容warpctc和tf的ctc。
