### ISSUE TITLE
关于图像变长字符识别的问题

### ISSUE THREAD

**Issue by longmao-yiran** [ilovin/lstm_ctc_ocr#52]
看了您bate版本的代码，发现您虽然增加了自动补齐图片宽度的代码，但是您生成的验证码貌似都是一样长宽的，请问对于不定长字符识别您有做过吗

**Comment by ilovin** [comment]
我是 keep ratio处理的
https://github.com/ilovin/lstm_ctc_ocr/blob/beta/lib/lstm/utils/gen.py#L52
生成的原图一样大小的话，那是captcha的问题

**Comment by longmao-yiran** [comment]
我看到了您的代码keep ratio处理 ，只是想问下您是在哪设置的 使得captcha输出的图片为60*160的，十分感谢您的回复

**Comment by ilovin** [comment]
尺寸是你可以自己控制的

https://github.com/lepture/captcha/tree/master/captcha
