### ISSUE TITLE
time_steps.append(nw//cfg.POOL_SCALE+cfg.OFFSET_TIME_STEP)

### ISSUE THREAD

**Issue by SolinTao** [ilovin/lstm_ctc_ocr#56]
time_steps.append(nw//cfg.POOL_SCALE+cfg.OFFSET_TIME_STEP)
max_w = math.ceil(max_w/cfg.POOL_SCALE)*cfg.POOL_SCALE

你好，请问这两句是什么意思呢？为什么不是w呢？

**Comment by ilovin** [comment]
1. conv's padding : 'valid'，所以加了一个offset(lib/networks/LSTM_train.py)
2. 这应该是用来生成一个batch数据的，所以需要得到一个batch里的最大长度，将所有的img padding到同一大小。同时保证了该长度可以被POOL_SCALE整除
