### ISSUE TITLE
image preprocess

### ISSUE THREAD

**Issue by Gus-Guo** [ilovin/lstm_ctc_ocr#6]
您好，我看您说做了一个身份证识别的模型。我想请教你数据怎么预处理的，您那个模型是直接在身份证号码上面训练的吗？有涉及到处理反光问题吗？我最近在做一个表盘数字识别，用自己生成的数据训练，在表盘数字上测试结果很差

**Comment by ilovin** [comment]
是用自己生成的数据，没有涉及到反光问题
需要注意的是，生成的图片要和实际图片长得“类似“
可以尝试不同的生成方法，以及不同的字体

**Comment by Gus-Guo** [comment]
好的，谢谢您的建议。

发自我的 iPhone

在 2017年7月19日，下午1:53，Scott <notifications@github.com<mailto:notifications@github.com>> 写道：


是用自己生成的数据，没有涉及到反光问题
需要注意的是，生成的图片要和实际图片长得“类似“
可以尝试不同的生成方法，以及不同的字体
